<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class DemoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cards')->truncate();
        DB::table('promocodes')->truncate();
        DB::table('promocode_usages')->truncate();
        DB::table('provider_devices')->truncate();
        DB::table('provider_documents')->truncate();
        DB::table('provider_profiles')->truncate();
        DB::table('provider_services')->truncate();
        DB::table('request_filters')->truncate();
        DB::table('user_request_payments')->truncate();
        DB::table('user_request_ratings')->truncate();
        DB::table('user_requests')->truncate();
        DB::table('users')->truncate();
        DB::table('users')->insert([[
            'first_name' => 'eganow',
            'last_name' => 'Demo',
            'email' => 'demo@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Emilia',
            'last_name' => 'Epps',
            'email' => 'emilia@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Perry',
            'last_name' => 'Kingsley',
            'email' => 'perry@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Joseph',
            'last_name' => 'Garrison',
            'email' => 'joseph@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Ella',
            'last_name' => 'Morrissey',
            'email' => 'morrissey@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Elizabeth',
            'last_name' => 'Forshee',
            'email' => 'elizabeth@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Douglas',
            'last_name' => 'Arce',
            'email' => 'douglas@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Sara',
            'last_name' => 'Nixon',
            'email' => 'sara@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Edward',
            'last_name' => 'Jett',
            'email' => 'edward@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Marilyn',
            'last_name' => 'Bradley',
            'email' => 'marilyn@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Herman',
            'last_name' => 'Thompson',
            'email' => 'herman@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Darrin',
            'last_name' => 'Neely',
            'email' => 'darrin@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Ralph',
            'last_name' => 'Vaughn',
            'email' => 'ralph@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Arturo',
            'last_name' => 'Gibson',
            'email' => 'arturo@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Kevin',
            'last_name' => 'Delacruz',
            'email' => 'kevin@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Catherine',
            'last_name' => 'Ferguson',
            'email' => 'catherine@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Gary',
            'last_name' => 'Maple',
            'email' => 'gary@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Robert',
            'last_name' => 'Ferguson',
            'email' => 'robert@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Charles',
            'last_name' => 'Ferguson',
            'email' => 'charles@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Michael',
            'last_name' => 'Ferguson',
            'email' => 'michael@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Patrick',
            'last_name' => 'Ferguson',
            'email' => 'patrick@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Arturo',
            'last_name' => 'Arturo',
            'email' => 'arturon@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Anthony',
            'last_name' => 'Ken',
            'email' => 'ken@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Anthony',
            'last_name' => 'Clinton',
            'email' => 'clinton@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Gabriel',
            'last_name' => 'Ferguson',
            'email' => 'gabriel@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Gabriel',
            'last_name' => 'Scott',
            'email' => 'scott@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Raymon',
            'last_name' => 'Ferguson',
            'email' => 'raymon@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Shon',
            'last_name' => 'Ferguson',
            'email' => 'shon@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Dennis',
            'last_name' => 'Ferguson',
            'email' => 'dennis@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Wayne',
            'last_name' => 'Ferguson',
            'email' => 'wayne@eganow.com',
            'password' => bcrypt('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'picture' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ]]);

        DB::table('providers')->truncate();
        DB::table('providers')->insert([[
            'first_name' => 'eganow',
            'last_name' => 'Demo',
            'email' => 'demo@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Thomas',
            'last_name' => 'Jenkins',
            'email' => 'thomas@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Rachel',
            'last_name' => 'Burns',
            'email' => 'rachel@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Lorraine',
            'last_name' => 'Harris',
            'email' => 'lorraine@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Adam',
            'last_name' => 'Wagner',
            'email' => 'adam@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Christine',
            'last_name' => 'Forshee',
            'email' => 'christine@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Logan',
            'last_name' => 'Arce',
            'email' => 'logan@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Joe',
            'last_name' => 'Demo',
            'email' => 'joe@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Price',
            'last_name' => 'Jett',
            'email' => 'price@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Lloyd',
            'last_name' => 'Bradley',
            'email' => 'lloyd@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Evans',
            'last_name' => 'Thompson',
            'email' => 'evans@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Jerry',
            'last_name' => 'Neely',
            'email' => 'jerry@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Teresa',
            'last_name' => 'Vaughn',
            'email' => 'teresa@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Sarah',
            'last_name' => 'Gibson',
            'email' => 'sarah@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Regina',
            'last_name' => 'Delacruz',
            'email' => 'regina@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Anthony',
            'last_name' => 'Ferguson',
            'email' => 'anthony@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Gary',
            'last_name' => 'Maple',
            'email' => 'rasheed@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Robert',
            'last_name' => 'Ferguson',
            'email' => 'jack@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Charles',
            'last_name' => 'Ferguson',
            'email' => 'bobby@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Michael',
            'last_name' => 'Ferguson',
            'email' => 'chunky@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Patrick',
            'last_name' => 'Ferguson',
            'email' => 'silk@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Arturo',
            'last_name' => 'Arturo',
            'email' => 'gil@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Anthony',
            'last_name' => 'Ken',
            'email' => 'stego@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Anthony',
            'last_name' => 'Clinton',
            'email' => 'rodney@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Gabriel',
            'last_name' => 'Ferguson',
            'email' => 'spork@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Paul',
            'last_name' => 'Ferguson',
            'email' => 'paul@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Gabriel',
            'last_name' => 'Giuseppe',
            'email' => 'giuseppe@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Pog',
            'last_name' => 'Ferguson',
            'email' => 'pog@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Steve',
            'last_name' => 'Ferguson',
            'email' => 'steve@eganow.com ',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ],[
            'first_name' => 'Pog',
            'last_name' => 'AJJS',
            'email' => 'beauregard@eganow.com',
            'password' => bcrypt('123456'),
            'status' => 'approved',
            'latitude' => '13.00',
            'longitude' => '80.00',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'avatar' => 'http://lorempixel.com/512/512/business/Xuber-Services',
        ]]);

        DB::table('provider_services')->truncate();
        DB::table('provider_services')->insert([[
            'provider_id' => 1,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 2,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 3,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 4,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 5,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 6,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 7,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 8,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 9,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 10,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 11,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 12,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 13,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 14,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 15,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 16,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 17,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 18,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 19,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 20,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 21,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 22,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 23,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 24,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 25,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 26,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 27,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 28,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 29,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],[
            'provider_id' => 30,
            'service_type_id' => 1,
            'status' => 'active',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]]);
    }
}
