/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Layout from "../../components/layout";
import Link from "next/link";
import sendlogo from "../../assets/send.png";
import Image from "next/image";
import { Formik, Form, Field, ErrorMessage } from "formik";
import * as Yup from "yup";
import { CustomPushTable } from "../../components/customPush/CustomPushTable";
import Header from "@/components/header";
import Datepicker from "@/components/datepicker1";
import Picker from "@/components/dateRange";

type PushProp = {
  title: string;
  message: string;
  group: string;
  notification: string;
  device: string;
};

export default function customPush() {
  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header name="Custom Push/SMS"/>
        </div>
      </div>{" "}
      <Layout>
        <Head>
          <title>Custom Push/SMS</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          <section className="w- ">
            <div className="flex justify-between items-center">
              <p className="pt-[23px] pl-[21px] text-[22px] leading-[30px] font-medium text-[#262626] ">
                Custom Push/SMS
              </p>

              <Link href={""}>
                <button
                  type="button"
                  className="text-[#FFFFFF] border bg-[#007AF5] mt-[23px] rounded-[4px] w-[84px] border-[#DADADA] focus:outline-none text-xs py-1.5 text-center inline-flex justify-center font-normal items-center mr-5 mb-2"
                >
                  Send
                  <Image className="ml-[4px]" src={sendlogo} alt={""} />
                </button>
              </Link>
            </div>

            <div className="mt-3 rounded-lg [368px] mb-[33px] mx-6">
              <Formik<PushProp>
                initialValues={{
                  title: "",
                  message: "",
                  group: "",
                  notification: "",
                  device: "",
                }}
                validationSchema={Yup.object({
                  message: Yup.string()
                    .max(20, "Must be 40 characters or less")
                    .required("Message required"),

                  title: Yup.string().required("Message required"),
                  group: Yup.string().required("Required field"),
                  notification: Yup.string().required("Required field"),
                  device: Yup.string().required("Required field"),
                })}
                onSubmit={async (values) => {
                  alert(JSON.stringify(values, null, 2));
                }}
              >
                {({ handleSubmit, values, handleChange, setFieldValue }) => (
                  <Form
                    onSubmit={handleSubmit}
                    className="bg-white rounded-lg px-[1rem] pb-10"
                  >
                    <div className="flex w-full space-x-5">
                      <section className="w-[33%] ">
                        <label
                          htmlFor="group"
                          className="block mb-2 text-sm pt-[10px] font-medium text-gray-900"
                        >
                          Select Group to Send
                        </label>
                        <Field
                          id="group"
                          as="select"
                          className="bg-[#FFFFFF] border grow border-[#D9D9D9] placeholder-[#BFBFBF] text-gray-900 text-sm rounded-[4px] block w-full py-1.5 "
                          value={values.group}
                          onChange={handleChange}
                        >
                          <option disabled={true} value={""}>
                            Select group
                          </option>
                          <option>All Drivers</option>
                          <option>Online Drivers</option>
                          <option>Offline Drivers</option>
                          <option>DriveNow Drivers</option>
                        </Field>
                        <p className="font-medium text-xs text-red-700">
                          <ErrorMessage name="group" />
                        </p>
                      </section>
                      <section className="w-[33%]">
                        <label
                          htmlFor="notification"
                          className="block mb-2 text-sm pt-[10px] font-medium text-gray-900"
                        >
                          Select Notification Type
                        </label>
                        <Field
                          id="notification"
                          as="select"
                          className="bg-[#FFFFFF] border border-[#D9D9D9] placeholder-[#BFBFBF] text-gray-900 text-sm rounded-[4px] block w-full p-1.5 "
                          value={values.notification}
                          onChange={handleChange}
                        >
                          <option disabled={true} value={""}>
                            Select notification type
                          </option>
                          <option>SMS Notification</option>
                          <option>PUSH Notification</option>
                          <option>SMS/PUSH Notification</option>
                        </Field>
                        <p className="font-medium text-xs text-red-700">
                          <ErrorMessage name="notification" />
                        </p>
                      </section>
                      <section className="w-[33%]">
                        <label
                          htmlFor="device"
                          className="block mb-2 text-sm pt-[10px] font-medium text-gray-900"
                        >
                          Select Device Type
                        </label>
                        <Field
                          id="device"
                          as="select"
                          className="bg-[#FFFFFF] border border-[#D9D9D9] placeholder-[#BFBFBF] text-gray-900 text-sm rounded-[4px] block w-full p-1.5 "
                          value={values.device}
                          onChange={handleChange}
                        >
                          <option disabled={true} value={""}>
                            Select Device
                          </option>
                          <option>Android</option>
                          <option>IOS</option>
                          <option>Both</option>
                        </Field>
                        <p className="font-medium text-xs text-red-700">
                          <ErrorMessage name="device" />
                        </p>
                      </section>
                    </div>
                    <div className="flex mt-4 gap-x-4">
                      <div className="w-[50%]">
                        <label
                          htmlFor="title"
                          className="block mb-2 text-sm font-medium text-[#000000]"
                        >
                          Select Date
                        </label>
                        <Picker />
                      </div>

                      <div className="w-[50%]">
                        <label
                          htmlFor="title"
                          className="block mb-2 text-sm font-medium text-[#000000]"
                        >
                          Message Title
                        </label>
                        <Field
                          type="text"
                          id="title"
                          className="border border-gray-300 placeholder-[#BFBFBF] text-gray-900 text-sm rounded block w-full p-1.5"
                          placeholder="Title"
                          value={values.title}
                          onChange={handleChange}
                        />
                        <p className="font-medium text-xs text-red-700">
                          <ErrorMessage name="title" />
                        </p>
                      </div>
                    </div>
                    <div className="mt-2">
                      <label
                        htmlFor="message"
                        className="block mb-2 text-sm pt-[10px] font-medium text-gray-900"
                      >
                        Compose Notification Message
                      </label>
                      <Field
                        id="message"
                        as="textarea"
                        rows={10}
                        className="block p-2.5 mb-auto w-[100%] h-[100px] text-sm text-gray-900 bg-[#FFFFFF] rounded-[4px] border border-gray-300"
                        placeholder="Type your message here..."
                        value={values.message}
                        onChange={handleChange}
                      />
                      <p className="font-medium text-xs text-red-700">
                        <ErrorMessage name="message" />
                      </p>
                    </div>

                    <Link href={""}>
                      <button
                        type="button"
                        className="text-[#FFFFFF] border bg-[#007AF5]  mt-[2%] rounded-[4px] w-[84px] border-[#DADADA] focus:outline-none text-xs py-1.5 text-center inline-flex justify-center font-normal items-center ml-[] mr-2 mb-2"
                      >
                        Send
                        <Image className="ml-[4px]" src={sendlogo} alt={""} />
                      </button>
                    </Link>
                  </Form>
                )}
              </Formik>
            </div>

            <div className="mb-[50px] mx-5 rounded-lg pb-4 pt-3 bg-white ">
              <h3 className="text-[#262626] font-medium text-[22px] pt-4 pl-[10px] leading-[30px]">
                Custom Push History
              </h3>
              <CustomPushTable />
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
