/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import Head from "next/head";
import Layout from "../../components/layout";
import DoughnutChart from "../../components/Expense/ExpenseDoughnut";
import payment from "../../assets/payment.svg";
import declined from "../../assets/decline.svg";
import ExpenseStack from "../../components/Expense/ExpenseStackedChart";
import ExpenseTiles from "@/components/Expense/ExpenseTiles";
import { ExpenseTable } from "../../components/Expense/ExpenseTable";

import BasicStacking from "@/components/stackedChart";
import Header from "@/components/header";
import {
  CategoryDropdown,
  MonthDropdown,
  YearDropdown,
} from "@/components/chartDropdown";

export default function Expense() {
  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header name="Expense" />
        </div>
      </div>

      <Layout>
        <Head>
          <title>Expense</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full flex">
            <div className="flex grow gap-x-4 pr-5 ml-5 mt-5">
              <ExpenseTiles
                icon={payment}
                entity1="Total Expenses (Paid)"
                entity1value={1250}
                entity1differential={+15.8}
                entity2="Approved Expenses"
                entity2value={1180}
              />

              <ExpenseTiles
                icon={declined}
                entity1="Total Expenses (Declined)"
                entity1value={20}
                entity1differential={+5.8}
                entity2="Pending Expenses"
                entity2value={450}
              />
            </div>
          </section>

          <section className="flex">
            <div className="bg-white ml-5 mt-6 px-6 rounded-lg w-[62.03%] h-[500px]">
              <div>
                <div className="flex justify-between items-center pt-6 pb-4 ">
                  <h6 className="text-[#262626] font-bold leading-[14.06px] text-sm">
                    Expense Insights
                  </h6>
                  <div className="flex gap-x-0">
                    <CategoryDropdown />
                    <YearDropdown />
                  </div>
                </div>
              </div>
              <div>
                <ExpenseStack />
              </div>

              <div className="flex gap-x-12 mt-5 justify-center ">
                <div className="flex">
                  <div className="h-[14px] w-[18px] rounded-[3px] bg-[#0076EC]"></div>
                  <p className="font-normal text-xs pl-1 leading-[14px] text-[#585858]">
                    Expense Paid
                  </p>
                </div>

                <div className="flex">
                  <div className="h-[14px] w-[18px] rounded-[3px] bg-[#BDE6FF]"></div>
                  <p className="font-normal text-xs pl-1 leading-[14px] text-[#585858]">
                    Expense Not Paid
                  </p>
                </div>
              </div>
            </div>
            <section className="bg-white mt-6 ml-4 w-[38%] h-[500px] rounded-[8px] mr-5">
              <div className="flex justify-between">
                <h4 className="p-6 font-bold text-sm text-[#262626] leading-[21.6px]   ">
                  Expense Overview
                </h4>
                <div className="flex">
                  <CategoryDropdown />
                  <MonthDropdown />
                  <YearDropdown />
                </div>
              </div>
              <div className="flex justify-center mt-[24px]">
                <DoughnutChart />
              </div>

              <div className="flex px-4 mt-6 gap-3 flex-wrap">
                <div className="flex items-center leading-4 text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#0076EC] rounded-[50%]"></div>
                  Car Insurance
                </div>
                <div className="flex items-center leading-4 text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#492FB2] rounded-[50%]"></div>
                  Deposit Refund
                </div>
                <div className="flex items-center text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#CD39E5] rounded-[50%]"></div>
                  Petty Cash
                </div>
                <div className="flex items-center text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#19C098] rounded-[50%]"></div>
                  Utilities
                </div>
                <div className="flex items-center text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#FFA723] rounded-[50%]"></div>
                  Stationaries
                </div>
                <div className="flex items-center text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#0E7CFF] rounded-[50%]"></div>
                  Employee Transportation
                </div>
                <div className="flex items-center text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#FF2C91] rounded-[50%]"></div>
                  System
                </div>
                <div className="flex items-center text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#83E521] rounded-[50%]"></div>
                  Staff Costs
                </div>
                <div className="flex items-center text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#3FBBD7] rounded-[50%]"></div>
                  Driver Support
                </div>
                <div className="flex items-center text-xs rounded-[4px] border border-[#E6E6E6] py-[2px] px-3">
                  <div className="w-[10px] mr-1 h-[10px] border bg-[#FB3232] rounded-[50%]"></div>
                  General Vehicle Maintenance
                </div>
              </div>
            </section>
          </section>

          {/* Table */}
          <div className="bg-white mt-4 rounded-[8px] mb-[67px] px-[10px] mx-5 ">
            <h3 className="text-[22px] font-medium leading-[30px] pt-4 text-[#262626] ">
              Expense History
            </h3>

            <ExpenseTable />
          </div>
        </main>
      </Layout>
    </>
  );
}
