/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import Head from "next/head";
import Layout from "../../components/layout";
import Maps from "@/components/maps";
import DriverActivities from "@/components/Heatmap/DriverActivities";
import Header from "@/components/header";

export default function Heatmap() {
  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header />
        </div>
      </div>
      <Layout>
        <Head>
          <title>Heatmap</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full  xg:min-h-screen">
          <section className="w-full h-[860px] mb-0">
            <div className="absolute w-full">
              <Maps />
            </div>
            <div className="w-[22%] shadow-[opx_0px_12.8px_0px_#1B28361A] rounded-[4px] overflow-y-scroll no-scrollbar p-4 mt-[138px] h-[770px] inset-y-0 right-0 z-10 absolute bg-white mb-0 ">
              <h3 className="text-[#595959] text-2xl font-medium leading-7 ">
                Driver Activities
              </h3>
              <div>
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Offline"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Offline"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Offline"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
