/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import Head from "next/head";
import Layout from "../../components/layout";
import Link from "next/link";
import Image from "next/image";
import driver from "../../assets/driver_icon.png";
import vehicle from "../../assets/vehicle_icon.png";
import payment from "../../assets/payments.png";
import { DashboardTiles1 } from "@/components/tiles";
import DashboardTiles from "@/components/tiles";
import revenue from "../../assets/revenue_icon.png";
import { Grid } from "@mui/material";
import { gridSpacing } from "../../components/revenueChart/constant";
import BasicStacking from "@/components/stackedChart";

export default function Dashboard() {
  return (
    <>
      <Layout>
        <Head>
          <title>Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full flex">
<div className="">
    
    </div>              
          </section>
        </main>
      </Layout>
    </>
  );
}
