/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import Head from "next/head";
import Layout from "../../components/layout";
import Maps from "@/components/maps";
import DriverActivities from "@/components/Heatmap/DriverActivities";
import Header from "@/components/header";

export default function Heatmap() {
  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header name="Heatmap" />
        </div>
      </div>
      <Layout>
        <Head>
          <title>Heatmap</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-white border-0 w-full xg:min-h-screen">
          <section className="w-full relative bg-white border-0 mb-0">
            <div className="w-full mb-0">
              <Maps />
            </div>
            <div className="w-[25%] shadow-[opx_0px_12.8px_0px_#1B28361A] rounded-[4px] overflow-y-scroll no-scrollbar pt-0 pb-4 mt-[7.5%] h-[82.5%] inset-y-0 right-0 z-10 absolute bg-white dark:bg-gray-700 mb-0 ">
              <div className="bg-white dark:bg-gray-700 pt-4 static rounded-t-[4px] w-full  pl-4">
                <h3 className="text-[#595959] dark:text-white text-2xl  font-medium leading-7 ">
                  Driver Activities
                </h3>
              </div>
              <div className="px-4 mt-10">
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Offline"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Offline"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Offline"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
                <DriverActivities
                  name="Frank Mensah"
                  rating="100%"
                  lastUpdate="Updated 5 mins ago"
                  status="Online"
                />
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
