/* eslint-disable require-jsdoc */

/* eslint-disable react/no-unescaped-entities */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import Head from "next/head";
import Layout from "../../../components/layout";
import DrivenowInvoicesTiles, {
  DrivenowInvoicesTiles1,
  LastTile,
} from "../../../components/DriveNowInvoices/DrivenowTiles";
import { DrivenowInvoicesTable } from "../../../components/DriveNowInvoices/DrivenowInvoices";
import Link from "next/link";
import Image from "next/image";
import { TableRange } from "@/components/dateRange";
import driver from "../../../assets/driver.svg";
import revenue from "../../../assets/revenue.svg";
import vehicle from "../../../assets/vehicle_icon.png";
import payment from "../../../assets/payment.svg";
import Header from "@/components/header";
import { DriveNowInvoicesDropdown } from "@/components/paymentDropdown";

export default function DriveNowInvoices() {
  return (
    <>
      <Header name="Drivenow Invoices" />
      <Layout>
        <Head>
          <title>DriveNow Invoices</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] dark:bg-dm-600 w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full ">
            <div className="flex space-x-4 grow m-5 max-2xl:m-4">
              <DrivenowInvoicesTiles1
                icon={revenue}
                entity1="Total Amount Received"
                entity1value={2412570.0}
                entity2="Total Daily"
                entity2value={450}
                entity2differential={20.0}
              />
              <DrivenowInvoicesTiles
                icon={driver}
                entity1="Total Drivers"
                entity1value={1250}
                entity1differential={+15.8}
                entity2differential={+15.8}
                entity2="Defaulted Drivers"
                entity2value={1180}
                entity3="Blocked Drivers"
                entity3value={70}
                entity3differential={-4.9}
              />
              <LastTile
                icon={payment}
                entity1="Total Transactions"
                entity1value={450}
                entity2="Completed"
                entity2value={445}
                entity3="Failed"
                entity3value={5}
              />
            </div>

            {/* Table */}

            <div className="bg-white dark:bg-dm-700 rounded-lg mx-5 max-2xl:mx-4 px-[10px] mb-[142px] mt-6 max-2xl:mt-4 ">
              <div className="flex pt-4 justify-between ">
                <h1 className="text-[#262626] dark:text-white font-medium leading-[30px] ">
                  Invoice Generated History
                </h1>
                <div className="h-[10px] mt-[3px]">
                  <TableRange />
                </div>
              </div>
              <div className="mt-9 relative">
                <DriveNowInvoicesDropdown />
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
