/* eslint-disable require-jsdoc */

/* eslint-disable react/no-unescaped-entities */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import Head from "next/head";
import Layout from "../../../components/layout";
import DrivenowInvoicesTiles, {
  DrivenowInvoicesTiles1,
} from "../../../components/DriveNowInvoices/DrivenowTiles";
import { DrivenowInvoicesTable } from "../../../components/DriveNowInvoices/DrivenowInvoices";
import Link from "next/link";
import Image from "next/image";
import driver from "../../../assets/driver.svg";
import revenue from "../../../assets/revenue.svg";
import vehicle from "../../../assets/vehicle_icon.png";
import payment from "../../../assets/payment.svg";
import Header from "@/components/header";

export default function DriveNowInvoices() {
  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header name="Drivenow Invoices" />
        </div>
      </div>
      <Layout>
        <Head>
          <title>DriveNow Invoices</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full ">
            <div className="flex space-x-4 grow m-5">
              <DrivenowInvoicesTiles1
                icon={revenue}
                entity1="Total Amount Received"
                entity1value={2412570.0}
                entity2="Total Daily"
                entity2value={450}
                entity2differential="+20.00%"
              />
              <DrivenowInvoicesTiles
                icon={driver}
                entity1="Total Drivers"
                entity1value={1250}
                entity1differential="+15.80%"
                entity2="Online Drivers"
                entity2value={1180}
                entity3="Offline Drivers"
                entity3value={70}
                entity3differential="-4.90%"
              />
              <DrivenowInvoicesTiles
                icon={payment}
                entity1="Total Payments"
                entity1value={450}
                entity2="Completed"
                entity2value={445}
                entity3="Failed"
                entity3value={5}
              />
            </div>

            {/* Table */}

            <div className="bg-white rounded-lg mx-5 px-[10px] mb-12 mt-6 ">
              <DrivenowInvoicesTable />
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
