/* eslint-disable require-jsdoc */
/* eslint-disable react/no-unescaped-entities */
import React, { useState } from "react";
import Head from "next/head";
import Layout from "../../../components/layout";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import PaymentTiles, {
  LastTile,
  MidTiles,
} from "../../../components/payment/paymentTiles";
import { BasicTable } from "../../../components/payment/BasicTable";
import { DailyPaymentsTable } from "../../../components/payment/DailyPayments/DailyPaymentsTable";
import { PaymentTransactionsTable } from "../../../components/payment/PaymentTransactions/PaymentTransactionsTable";

import Link from "next/link";
import Image from "next/image";
import driver from "../../../assets/driver.svg";
import revenue from "../../../assets/revenue.svg";
import vehicle from "../../../assets/vehicle.svg";
import payment from "../../../assets/payment.svg";
import bell from "../../../assets/paymentbell.svg";
import Header from "@/components/header";
import PaymentsDropdown from "../../../components/paymentDropdown";
export default function Payments() {
  return (
    <>
      <Header name="Payments" />
      <Layout>
        <Head>
          <title>Payments</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] dark:bg-dm-600 w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full ">
            <div className="flex space-x-4 grow m-5 max-2xl:m-4">
              <PaymentTiles
                icon={revenue}
                entity1="Total Amount Received"
                entity1value={2412570.0}
                entity1differential={+15.8}
                entity2="Total Daily"
                entity2value={450}
                entity2differential={+4.9}
              />
              <MidTiles
                icon={driver}
                entity1="Total Drivers"
                entity1value={1250}
                entity2="Defaulted Drivers"
                entity2value={1180}
                entity3="Blocked Drivers"
                entity3value={70}
                entity1differential={+15.8}
                entity2differential={-4.9}
                entity3differential={+4.9}
              />
              <LastTile
                icon={payment}
                entity1="Total Transactions"
                entity1value={450}
                entity2="Completed"
                entity2value={445}
                entity3="Failed"
                entity3value={5}
              />
            </div>

            {/* Table */}

            <div className="bg-white  dark:bg-dm-700 rounded-lg mx-5 max-2xl:mx-4 px-[10px] pb-4 mb-[140px] mt-6 max-2xl:mt-4 ">
              <div className="flex justify-between ">
                <h1 className="text-[#262626] dark:text-white font-medium leading-[30px] pl-[] pt-4 ">
                  Payments
                </h1>
                <Link href={""}>
                  <button
                    type="button"
                    className="text-[#FFFFFF] border mt-4 bg-[#007AF5] dark:border-0 rounded-[4px] focus:outline-none text-sm px-4 py-1.5 text-center inline-flex justify-center font-normal items-center cursor-pointer mb-2 "
                  >
                    <Image src={bell} alt="bell icon" className="ml-0 mr-1" />
                    Send Payment Reminder
                  </button>
                </Link>
              </div>

              <div className="mt-7 relative">
                <PaymentsDropdown />
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
