/* eslint-disable require-jsdoc */
/* eslint-disable react/no-unescaped-entities */
import React from "react";
import Head from "next/head";
import Layout from "../../../components/layout";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import AllDriverTiles from "@/components/Drivers/DriverTiles";
import { BasicTable } from "../../../components/payment/BasicTable";
import Link from "next/link";
import Image from "next/image";
import driver from "../../../assets/driver_icon.png";
import vehicle from "../../../assets/vehicle_icon.png";
import payment from "../../../assets/payments.png";
import bell from "../../../assets/bell_icon.png";
import Header from "@/components/header";

export default function Payments() {
  return (
    <>
<div className="flex w-full">
        <div className="w-full z-10">
          <Header name="Payments" />
        </div>
      </div>
      <Layout>
        <Head>
          <title>Payments</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full ">
            <div className="flex space-x-4 grow m-5">
              <AllDriverTiles
                icon={vehicle}
                entity1="Total Vehicles"
                entity1value={1250}
                entity1differential="+15.80%"
                entity2="Active Vehicles"
                entity2value={1180}
                entity2differential="+4.90%"
                entity3="Damaged"
                entity3value={70}
                entity3differential="-4.90%"
              />
              <AllDriverTiles
                icon={driver}
                entity1="Total Drivers"
                entity1value={1250}
                entity1differential="+15.80%"
                entity2="Online Drivers"
                entity2value={1180}
                entity3="Offline Drivers"
                entity3value={70}
                entity3differential="-4.90%"
              />
              <AllDriverTiles
                icon={payment}
                entity1="Total Payments"
                entity1value={450}
                entity2="Completed"
                entity2value={445}
                entity3="Failed"
                entity3value={5}
              />
            </div>

            {/* Table */}

            <div className="bg-white rounded-lg mx-5 pb-4 mb-12 mt-6 ">
              <div className="flex justify-between ">
                <h4 className="text-[#262626] font-medium text-[22px] leading-[30px] pl-[10px] pt-4 ">
                  Payments
                </h4>
                <Link href={"/views/"}>
                  <button
                    type="button"
                    className="text-[#FFFFFF] border mt-4 bg-[#007AF5] rounded-[4px] w-[] focus:outline-none text-sm px-4 py-1.5 text-[14px] text-center inline-flex justify-center font-normal items-center mr-5 mb-2 "
                  >
                    <Image src={bell} alt="bell icon" className="ml-0 mr-1" />
                    Send Payment Reminder
                  </button>
                </Link>
              </div>
              <BasicTable />
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
