/* eslint-disable require-jsdoc */
/* eslint-disable react/no-unescaped-entities */
import React from "react";
import Head from "next/head";
import Layout from "../../../components/layout";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import PaymentTiles, { LastTile, MidTiles } from "../../../components/payment/paymentTiles";
import { BasicTable } from "../../../components/payment/BasicTable";
import Link from "next/link";
import Image from "next/image";
import driver from "../../../assets/driver.svg";
import revenue from "../../../assets/revenue.svg";
import vehicle from "../../../assets/vehicle.svg";
import payment from "../../../assets/payment.svg";
import bell from "../../../assets/paymentbell.svg";
import Header from "@/components/header";

export default function Payments() {
  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header name="Payments" />
        </div>
      </div>
      <Layout>
        <Head>
          <title>Payments</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full ">
            <div className="flex space-x-4 grow m-5">
              <PaymentTiles
                icon={revenue}
                entity1="Total Amount Received"
                entity1value={2412570.00}
                entity1differential={+15.80}
                entity2="Total Daily"
                entity2value={450}
                entity2differential={+4.90}
                
              />
              <MidTiles
                icon={driver}
                entity1="Total Drivers"
                entity1value={1250}             
                entity2="Defaulted Drivers"
                entity2value={1180}
                entity3="Blocked Drivers"
                entity3value={70}
                entity1differential={+15.80}
                entity2differential={-4.90}
                entity3differential={+4.90}
              />
              <LastTile
                icon={payment}
                entity1="Total Transactions"
                entity1value={450}
                entity2="Completed"
                entity2value={445}
                entity3="Failed"
                entity3value={5}
              />
            </div>

            {/* Table */}

            <div className="bg-white rounded-lg mx-5 px-[10px] pb-4 mb-12 mt-6 ">
              <div className="flex justify-between ">
                <h4 className="text-[#262626] font-medium text-[22px] leading-[30px] pl-[] pt-4 ">
                  Payments
                </h4>
                <Link href={"/views/"}>
                  <button
                    type="button"
                    className="text-[#FFFFFF] border mt-4 bg-[#007AF5] rounded-[4px] w-[] focus:outline-none text-sm px-4 py-1.5 text-[14px] text-center inline-flex justify-center font-normal items-center mb-2 "
                  >
                    <Image src={bell} alt="bell icon" className="ml-0 mr-1" />
                    Send Payment Reminder
                  </button>
                </Link>
              </div>
              <BasicTable />
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
