/* eslint-disable require-jsdoc */

/* eslint-disable react/no-unescaped-entities */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import { Formik, Field, Form, ErrorMessage } from "formik";
import * as Yup from "yup";
import Head from "next/head";
import Layout from "../../../../components/layout";
import blueline from "../../../../assets/Line 11.png";
import greyline from "../../../../assets/greyline.png";
import greenline from "../../../../assets/greenline.png";

import StyledDropzone from "../../../../components/dropzone";
import CheckOutlinedIcon from "@mui/icons-material/CheckOutlined";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import AllDriverTiles from "@/components/Drivers/DriverTiles";
import Link from "next/link";
import Image from "next/image";
import info from "../../../../assets/info_icon.png";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import driver from "../../../assets/driver_icon.png";
import plus from "../../../../assets/plus.png";
import vehicle from "../../../assets/vehicle_icon.png";
import payment from "../../../assets/payments.png";
import { DashboardTiles1 } from "@/components/tiles";
import DashboardTiles from "@/components/tiles";
import AccountMenu from "@/components/headerDropdown";
import { Grid } from "@mui/material";
// import { gridSpacing } from "../components/revenueChart/constant";
import BasicStacking from "@/components/stackedChart";
import Header from "@/components/header";

type GuarantorProps = {
  houseAddress: string;
  phone: string;
  ghanaCardName: string;
  ghanaCardNumber: string;
  gpsAddress: string;
};

type UploadModel = {
  documents?: any;
};

export default function GuarantorDetails(prop: GuarantorProps) {
  const phoneRegExp =
    /^((\+[1-9]{1,4}[ -]?)|(\([0-9]{2,3}\)[ -]?)|([0-9]{2,4})[ -]?)*?[0-9]{3,4}[ -]?[0-9]{3,4}$/;

  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header name="All Drivers" secondName=" / Drivers KYC" />{" "}
        </div>
      </div>{" "}
      <Layout>
        <Head>
          <title>Add New Driver</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="bg-white rounded-lg m-[19px] p-4 mb-[47px]">
            <div className="pb-4">
              <h3 className="font-medium text-[22px] leading-[30px] text-[#262626]">
                Driver KYC
              </h3>
              <p className="text-[#737373] font-medium leading-[30px] text-base">
                Complete this form to initiate background checks, ensuring we
                meet regulatory requirements and protect our business from
                potential risks.
              </p>
            </div>
            {/* Timeline */}
            <div className="flex py-10 px-[44px] border-y items-center">
              <div className="bg-[#0C9064] flex items-center justify-center  w-8 h-8 text-white rounded-[100%] ">
                <CheckOutlinedIcon fontSize="small" />
              </div>
              <p className="pl-[10px] font-bold text-sm leading-[30px] text-[#0C9064]">
                Personal Details
              </p>
              <Image
                src={greenline}
                alt="blue timeline"
                className="w-[100px] ml-1 grow"
              />
              <div className="bg-[#0C9064] flex items-center justify-center ml-1 w-8 h-8 text-white rounded-[100%] ">
                <CheckOutlinedIcon fontSize="small" />
              </div>
              <p className="pl-[10px] font-bold text-sm leading-[30px] text-[#0C9064]">
                Residence Details{" "}
              </p>
              <Image
                src={greenline}
                alt="blue timeline"
                className="w-[100px] ml-1 grow"
              />
              <div className="bg-[#007AF5] flex items-center justify-center ml-1 w-8 h-8 text-white rounded-[100%] ">
                3
              </div>
              <p className="pl-[10px] font-bold text-sm leading-[30px] text-[#007AF5]">
                Guarantor Details{" "}
              </p>
              <Image
                src={greyline}
                alt="blue timeline"
                className="w-[100px] ml-1 grow"
              />
              <div className="bg-[#8C8C8C] flex items-center justify-center ml-1 w-8 h-8 text-white rounded-[100%] ">
                4
              </div>
              <p className="pl-[10px] font-bold text-sm leading-[30px] text-[#8C8C8C]">
                Relative Details{" "}
              </p>
            </div>

            <h3 className="font-medium leading-[30px] pt-4 text-lg text-[#262626]">
              Identification Details (Guarantor)
            </h3>

            <div className="mb-12 border-0">
              <Formik<GuarantorProps>
                initialValues={{
                  phone: "",
                  ghanaCardName: "",
                  gpsAddress: "",
                  houseAddress: "",
                  ghanaCardNumber: "",
                }}
                validationSchema={Yup.object({
                  phone: Yup.string()
                    .matches(phoneRegExp, "Invalid Phone number")
                    .required("Required Field"),
                  houseAddress: Yup.string().required("Required field"),
                  ghanaCardNumber: Yup.string().required("Required field"),
                  gpsAddress: Yup.string().required("Required field"),
                  ghanaCardName: Yup.string().required("Required field"),
                })}
                onSubmit={async (values) => {
                  alert(JSON.stringify(values, null, 2));
                }}
              >
                {({ handleSubmit, values, handleChange, setFieldValue }) => (
                  <Form
                    onSubmit={handleSubmit}
                    className="bg-white border-0 pb-10"
                  >
                    <section className="">
                      <div className="flex gap-x-4 mt-3 w-full">
                        {/* Ghana Card Name */}
                        <div className="w-[50%]">
                          <label
                            htmlFor="ghanaCardName"
                            className="block mb-2 text-sm font-medium text-gray-900"
                          >
                            Ghana Card Name{" "}
                          </label>
                          <Field
                            type="text"
                            id="ghanaCardName"
                            className="border placeholder-[#BFBFBF] shadow-[0px_1px_2px_0px_#1B283614] border-gray-300 text-gray-900 text-sm rounded block w-full p-2"
                            placeholder="Full name"
                            value={values.ghanaCardName}
                            onChange={handleChange}
                          />
                          <p className="font-medium text-xs text-red-700">
                            <ErrorMessage name="ghanaCardName" />
                          </p>
                          <p className="text-[#737373] text-sm font-normal leading-[30px] pt-1">
                            Enter name as seen on the Ghana Card.
                          </p>
                        </div>

                        {/* Ghana Card Number */}
                        <div className="w-[50%]">
                          <label
                            htmlFor="ghanaCardNumber"
                            className="block mb-2 text-sm font-medium text-gray-900"
                          >
                            Street Name{" "}
                          </label>
                          <Field
                            type="text"
                            id="ghanaCardNumber"
                            className="border border-gray-300 placeholder-[#BFBFBF] shadow-[0px_1px_2px_0px_#1B283614] text-gray-900 text-sm rounded block w-full p-2"
                            placeholder="GHA-12345678-42"
                            value={values.ghanaCardNumber}
                            onChange={handleChange}
                          />
                          <p className="font-medium text-xs text-red-700">
                            <ErrorMessage name="ghanaCardNumber" />
                          </p>
                          <p className="text-[#737373] text-sm font-normal leading-[30px] pt-1">
                            Enter the Ghana Card number beginning with the GHA
                            prefix
                          </p>
                        </div>
                      </div>

                      <div className="flex gap-x-4 mt-5 ">
                        {/* Phone Number */}
                        <div className="w-[50%]">
                          <label
                            htmlFor="phone"
                            className="block mb-2 text-sm font-medium text-[#04030F]"
                          >
                            Phone
                          </label>
                          <Field
                            type="text"
                            id="phone"
                            className="border border-gray-300 placeholder-[#BFBFBF] shadow-[0px_1px_2px_0px_#1B283614] text-gray-900 text-sm rounded block w-full p-2"
                            placeholder="+233 123 456 789"
                            value={values.phone}
                            onChange={handleChange}
                          />
                          <p className="font-medium text-xs text-red-700">
                            <ErrorMessage name="phone" />
                          </p>
                          <p className="text-[#737373] text-sm font-normal leading-[30px] pt-1">
                            Enter phone number
                          </p>
                        </div>

                        {/* House Address */}
                        <div className="w-[50%]">
                          <label
                            htmlFor="houseAddress"
                            className="block mb-2 text-sm font-medium text-gray-900"
                          >
                            House Address{" "}
                          </label>
                          <Field
                            type="text"
                            id="houseAddress"
                            className="border border-gray-300 placeholder-[#BFBFBF] shadow-[0px_1px_2px_0px_#1B283614] text-gray-900 text-sm rounded block w-full p-2"
                            placeholder="Address"
                            value={values.houseAddress}
                            onChange={handleChange}
                          />
                          <p className="font-medium text-xs text-red-700">
                            <ErrorMessage name="houseAddress" />
                          </p>
                          <p className="text-[#737373] text-sm font-normal leading-[30px] pt-1">
                            Enter house address
                          </p>
                        </div>
                      </div>
                    </section>

                    {/* GPS Address */}
                    <div className="w-full mt-4">
                      <label
                        htmlFor="gpsAddress"
                        className="block mb-2 text-sm font-normal text-gray-900"
                      >
                        GPS Address
                      </label>
                      <Field
                        type="text"
                        id="gpsAddress"
                        className="border border-gray-300 placeholder-[#BFBFBF] shadow-[0px_1px_2px_0px_#1B283614] text-gray-900 w-full text-sm rounded block p-2"
                        placeholder="GT-123-456"
                        value={values.gpsAddress}
                        onChange={handleChange}
                      />
                      <p className="font-medium text-xs text-red-700">
                        <ErrorMessage name="gpsAddress" />
                      </p>
                      <p className="text-[#737373] text-sm font-normal leading-[30px] pt-1">
                        Enter Ghana Post Address
                      </p>
                    </div>

                    {/* Utility Bills */}
                    <section className="mt-5">
                      <p className="text-[#262626] pb-5 font-medium text-base leading-[30px] ">
                        Upload Image of Guarantor
                      </p>
                      <div className="ml-2">
                        <StyledDropzone />
                      </div>

                      <div className="flex mt-4 items-center">
                        <Image src={info} alt="info icon" className="w-4 h-4" />
                        <p className="text-[#737373] pl-1 font-normal leading-[30px] text-sm ">
                          Ensure that images uploaded are clear and details are
                          clearly captured.
                        </p>
                      </div>
                    </section>

                    <section className="mt-5">
                      <h3 className="text-[#262626] font-medium text-base leading-[30px] ">
                        Upload Ghana Card
                      </h3>

                      <div className="flex mt-4 space-x-5">
                        <div className="ml-2">
                          <StyledDropzone />
                          <p className="text-[#262626] font-medium text-base leading-[30px] ml-[38%] pt-2 ">
                            Front
                          </p>
                        </div>
                        <div className="ml-2">
                          <StyledDropzone />
                          <p className="text-[#262626] font-medium text-base leading-[30px] ml-[40%] pt-2 ">
                            Back
                          </p>
                        </div>
                      </div>

                      <div className="flex mt-3 items-center">
                        <Image src={info} alt="info icon" className="w-4 h-4" />
                        <p className="text-[#737373] pl-1 font-normal leading-[30px] text-sm ">
                          Ensure that images uploaded are clear and details are
                          clearly captured.
                        </p>
                      </div>
                    </section>

                    <div className="flex mt-5 justify-between">
                      <Link
                        href={"/views/Drivers/AddNewDriver/ResidentialDetails"}
                      >
                        <button
                          type="button"
                          className="text-[#FFFFFF] border bg-[#007AF5] ml-auto rounded-[4px] w-[85px] border-[#DADADA] focus:outline-none text-sm   py-1.5 text-center inline-flex justify-center font-normal items-center mr-5 mb-2 "
                        >
                          Previous
                        </button>
                      </Link>

                      <Link
                        href={"/views/Drivers/AddNewDriver/RelativeDetails"}
                      >
                        <button
                          type="button"
                          className="text-[#FFFFFF] border bg-[#007AF5] ml-auto rounded-[4px] w-[63px] border-[#DADADA] focus:outline-none text-sm py-1.5 text-center inline-flex justify-center font-normal items-center  mb-2 "
                        >
                          Next
                        </button>
                      </Link>
                    </div>
                  </Form>
                )}
              </Formik>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
