/* eslint-disable require-jsdoc */

/* eslint-disable react/no-unescaped-entities */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import { Formik, Field, Form, ErrorMessage } from "formik";
import * as Yup from "yup";
import Head from "next/head";
import Layout from "../../../../components/layout";
import blueline from "../../../../assets/Line 11.png";
import greyline from "../../../../assets/greyline.png";
import StyledDropzone from "../../../../components/dropzone";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import AllDriverTiles from "@/components/Drivers/DriverTiles";
import Link from "next/link";
import Image from "next/image";
import info from "../../../../assets/info_icon.png";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import driver from "../../../assets/driver_icon.png";
import plus from "../../../../assets/plus.png";
import vehicle from "../../../assets/vehicle_icon.png";
import payment from "../../../assets/payments.png";
import { DashboardTiles1 } from "@/components/tiles";
import DashboardTiles from "@/components/tiles";
import AccountMenu from "@/components/headerDropdown";
import { Grid } from "@mui/material";
// import { gridSpacing } from "../components/revenueChart/constant";
import BasicStacking from "@/components/stackedChart";
import Header from "@/components/header";

type PersonalProps = {
  firstName: string;
  lastName: string;
  phone: string;
  email: number | string;
  ghanaCardName: string;
  ghanaCardNumber: string;
  checked: any;
};

type UploadModel = {
  documents?: any;
};

export default function PersonalDetails(prop: PersonalProps) {
  const phoneRegExp =
    /^((\+[1-9]{1,4}[ -]?)|(\([0-9]{2,3}\)[ -]?)|([0-9]{2,4})[ -]?)*?[0-9]{3,4}[ -]?[0-9]{3,4}$/;

  return (
    <>
        <Header name="All Drivers  " />

      <Layout>
        <Head>
          <title>Add New Driver</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full ">
            <div className="bg-[#FFFFFF] mx-[19px] mt-[18px] ">
              <h3>Driver KYC</h3>
              <p>
                Complete this form to initiate background checks, ensuring we
                meet regulatory requirements and protect our business from
                potential risks.
              </p>

              {/* Timeline */}
              <div className="flex mx-4 py-10 px-[44px] border-y items-center">
                <div className="bg-[#007AF5] flex items-center justify-center  w-8 h-8 text-white rounded-[100%] ">
                  1
                </div>
                <p className="pl-[10px] font-bold text-sm leading-[30px] text-[#007AF5]">
                  Personal Details
                </p>
                <Image
                  src={blueline}
                  alt="blue timeline"
                  className="w-[100px] ml-1"
                />
                <div className="bg-[#8C8C8C] flex items-center justify-center ml-1 w-8 h-8 text-white rounded-[100%] ">
                  2
                </div>
                <p className="pl-[10px] font-bold text-sm leading-[30px] text-[#8C8C8C]">
                  Residence Details{" "}
                </p>
                <Image
                  src={greyline}
                  alt="blue timeline"
                  className="w-[100px] ml-1"
                />
                <div className="bg-[#8C8C8C] flex items-center justify-center ml-1 w-8 h-8 text-white rounded-[100%] ">
                  3
                </div>
                <p className="pl-[10px] font-bold text-sm leading-[30px] text-[#8C8C8C]">
                  Guarantor Details{" "}
                </p>
                <Image
                  src={greyline}
                  alt="blue timeline"
                  className="w-[100px] ml-1"
                />
                <div className="bg-[#8C8C8C] flex items-center justify-center ml-1 w-8 h-8 text-white rounded-[100%] ">
                  4
                </div>
                <p className="pl-[10px] font-bold text-sm leading-[30px] text-[#8C8C8C]">
                  Relative Details{" "}
                </p>
              </div>

              <h3 className="font-medium leading-[30px] text-lg text-[#262626] ">
                Personal Details (Driver)
              </h3>

              <div className="mt-10 mb-12 border-0 shadow mx-">
                <Formik<PersonalProps>
                  initialValues={{
                    firstName: "",
                    lastName: "",
                    phone: "",
                    email: "",
                    ghanaCardName: "",
                    ghanaCardNumber: "",
                    checked: [],
                  }}
                  validationSchema={Yup.object({
                    firstName: Yup.string()
                      .max(20, "Must be 40 characters or less")
                      .required("Required field"),
                    lastName: Yup.string().required("Required field"),
                    phone: Yup.string()
                      .matches(phoneRegExp, "Invalid Phone number")
                      .required("Required Field"),
                    email: Yup.string()
                      .email("Invalid email")
                      .required("Required field"),
                    ghanaCardName: Yup.string().required("Required field"),
                    ghanaCardNumber: Yup.string().required("Required field"),
                  })}
                  onSubmit={async (values) => {
                    alert(JSON.stringify(values, null, 2));
                  }}
                >
                  {({ handleSubmit, values, handleChange, setFieldValue }) => (
                    <Form
                      onSubmit={handleSubmit}
                      className="bg-white border-0 shadow-lg px-[2rem]  pb-10"
                    >
                      <section className="border-b">
                        <div className="flex w-full">
                          {/* First Name */}
                          <div className="mt-[1.875rem]">
                            <label
                              htmlFor="firstName"
                              className="block mb-2 text-sm font-normal text-gray-900"
                            >
                              First Name
                            </label>
                            <Field
                              type="text"
                              id="firstName"
                              className="border border-gray-300 text-gray-900 text-sm rounded2 block w-[500px] p-2"
                              placeholder="First Name"
                              value={values.firstName}
                              onChange={handleChange}
                            />
                            <p className="font-medium text-red-700">
                              <ErrorMessage name="firstName" />
                            </p>
                          </div>

                          {/* Last Name */}
                          <div className="mt-[1.875rem]">
                            <label
                              htmlFor="lastName"
                              className="block mb-2 text-sm font-normal text-gray-900"
                            >
                              Last Name
                            </label>
                            <Field
                              type="text"
                              id="lastName"
                              className="border border-gray-300 text-gray-900 text-sm rounded2 block w-[500px] p-2"
                              placeholder="Last Name"
                              value={values.lastName}
                              onChange={handleChange}
                            />
                            <p className="font-medium text-red-700">
                              <ErrorMessage name="lastName" />
                            </p>
                          </div>
                        </div>

                        <div className="flex">
                          <div className="mt-[1.25rem]">
                            <label
                              htmlFor="phone"
                              className="block mb-3 text-sm font-medium leading-[1.195rem] text-[#04030F]"
                            >
                              Phone
                            </label>
                            <Field
                              type="text"
                              id="phone"
                              className="border border-gray-300 text-gray-900 text-sm rounded block w-[480px] p-2.5"
                              placeholder="+233 123 456 789"
                              value={values.phone}
                              onChange={handleChange}
                            />
                            <p className="font-medium text-red-700">
                              <ErrorMessage name="phone" />
                            </p>
                          </div>

                          <div className="mt-[1.25rem]">
                            <label
                              htmlFor="email"
                              className="block mb-3 text-sm font-medium leading-[1.195rem] text-[#04030F]"
                            >
                              Email address
                            </label>
                            <Field
                              type="text"
                              id="email"
                              className="border border-gray-300 text-gray-900 text-sm rounded block w-[480px] p-2.5"
                              placeholder="example@email.com"
                              value={values.email}
                              onChange={handleChange}
                            />
                            <p className="font-medium text-red-700">
                              <ErrorMessage name="email" />
                            </p>
                          </div>
                        </div>
                      </section>

                      <h3 className="font-medium text-[#262626] text-lg ">
                        Identification Details
                      </h3>

                      <div className="flex">
                        <div className="mt-[1.875rem]">
                          <label
                            htmlFor="ghanaCardName"
                            className="block mb-2 font-medium text-base leading-[30px] text-[#262626]"
                          >
                            Ghana Card Name
                          </label>
                          <Field
                            type="text"
                            id="ghanaCardName"
                            className="border border-gray-300 text-gray-900 text-sm rounded2 block w-[500px] p-2"
                            placeholder="Full name"
                            value={values.ghanaCardName}
                            onChange={handleChange}
                          />
                          <p className="font-medium text-xs text-red-700">
                            <ErrorMessage name="ghanaCardNumber" />
                          </p>
                        </div>

                        <div className="mt-[1.875rem]">
                          <label
                            htmlFor="ghanaCardNumber"
                            className="block mb-2 text-sm font-normal text-gray-900"
                          >
                            Ghana Card Number
                          </label>
                          <Field
                            type="text"
                            id="ghanaCardNumber"
                            className="border border-gray-300 text-gray-900 text-sm rounded2 block w-[500px] p-2"
                            placeholder="GHA-12345678-42"
                            value={values.ghanaCardNumber}
                            onChange={handleChange}
                          />
                          <p className="font-medium text-xs text-red-700">
                            <ErrorMessage name="ghanaCardNumber" />
                          </p>
                        </div>
                      </div>

                      <div className="mt-5">
                        <h4 className="text-sm font-medium leading-[30px] text-[#262626] ">
                          Upload Selfie image
                        </h4>
                        <StyledDropzone />
                        <p className="pl-[30px] text-[#262626] text-base font-medium leading-[30px] pt-2 ">
                          Profile Picture
                        </p>
                        <div className="flex items-center">
                          <Image
                            src={info}
                            alt="info icon"
                            className="w-4 h-4"
                          />
                          <p className="text-[#737373] pl-1 font-normal leading-[30px] text-sm ">
                            Ensure that images uploaded are clear and details
                            are clearly captured.
                          </p>
                        </div>
                      </div>

                      <div>
                        <h4 className="font-medium text-base leading-[30px] text-[#262626] ">
                          Upload Ghana Card
                        </h4>
                        <div className="flex">
                          <StyledDropzone />
                          <StyledDropzone />
                        </div>
                        <div className="flex items-center">
                          <Image
                            src={info}
                            alt="info icon"
                            className="w-4 h-4"
                          />
                          <p className="text-[#737373] pl-1 font-normal leading-[30px] text-sm ">
                            Ensure that images uploaded are clear and details
                            are clearly captured.
                          </p>
                        </div>
                      </div>

                      <div className="flex justify-between ">
                        <button
                          type="button"
                          className="text-[#FFFFFF] border mt-[57px] bg-[#A6A6A6] rounded-[4px] w-[85px] border-[#DADADA] focus:outline-none text-sm   py-1.5 text-center inline-flex justify-center font-normal items-center mb-2 " disabled
                        >
                          Previous
                        </button>

                        <Link
                          href={
                            "/views/Drivers/AddNewDriver/ResidentialDetails"
                          }
                        >
                          <button
                            type="button"
                            className="text-[#FFFFFF] border mt-[57px] bg-[#007AF5] rounded-[4px] w-[63px] border-[#DADADA] focus:outline-none text-sm py-1.5 text-center inline-flex justify-center font-normal items-center mr-5 mb-2 "
                          >
                            Next
                          </button>
                        </Link>
                      </div>
                    </Form>
                  )}
                </Formik>
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
