/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import Head from "next/head";
import Layout from "../components/layout";
import Link from "next/link";
import Image from "next/image";
import driver from "../assets/driver_icon.png";
import vehicle from "../assets/vehicle_icon.png";
import payment from "../assets/payments.png";
import { DashboardTiles1 } from "@/components/tiles";
import DashboardTiles from "@/components/tiles";
import revenue from "../assets/revenue_icon.png";
import AccountMenu from "@/components/headerDropdown";
import { Grid } from "@mui/material";
// import { gridSpacing } from "../components/revenueChart/constant";
import BasicStacking from "@/components/stackedChart";

export default function Dashboard() {
  return (
    <>
      <Layout>
        <Head>
          <title>Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full flex">
            <div>
              <div className="ml-5 mt-5">
                <DashboardTiles
                  icon={revenue}
                  entity1="Revenue"
                  entity1value={2412570.0}
                  entity2="Total Payments"
                  entity2value={450}
                  entity2differential="+20.00%"
                />
              </div>

              <div className="ml-5 mt-5">
                <DashboardTiles
                  icon={revenue}
                  entity1="Revenue"
                  entity1value={2412570.0}
                  entity2="Total Payments"
                  entity2value={450}
                  entity2differential="+20.00%"
                />
              </div>
            </div>
            <div>
              <div className="ml-5 mt-5">
                <DashboardTiles
                  icon={driver}
                  entity1="Total Drivers"
                  entity1value={1250}
                  entity2="Active Drivers"
                  entity2value={1180}
                  entity2differential="-4.90%"
                  entity1differential="+15.80%"
                />
              </div>

              <div className="ml-5 mt-5">
                <DashboardTiles
                  icon={vehicle}
                  entity1="Total Vehicles"
                  entity1value={2412570.0}
                  entity2="Active Vehicles"
                  entity2value={450}
                  entity2differential="+20.00%"
                />
              </div>
            </div>

            <div className="">
              <div className="ml-5 mt-5">
                <DashboardTiles1
                  icon={payment}
                  entity1="Total Payments"
                  entity1value={450}
                  entity2="Failed"
                  entity2value={5}
                  entity3="Completed"
                  entity3value={445}
                />
              </div>
              <div className="ml-5 mt-5">
                <DashboardTiles1
                  icon={payment}
                  entity1="Total Payments"
                  entity1value={450}
                  entity2="Failed"
                  entity2value={5}
                  entity3="Completed"
                  entity3value={445}
                />
              </div>
            </div>
          </section>

          <section className="flex">
            <div className="ml-5 mt-6 w-[59.5%] h-[41rem] ">
              <BasicStacking />
            </div>

            <div className="mt-6 bg-[#FFFFFF] rounded-lg drop-shadow-smw   ml-[4%] pb-5 w-[30%] ">
              <div className="flex  ">
                <p className="m-5 text-base font-medium leading-[22px] text-[#262626] ">
                  Driver KYC
                </p>
              </div>
              <div className="ml-[6%]">
                <KYC
                  name="Frank Mensah"
                  description="Driver’s License Uploaded"
                  date="12 Sept"
                  status="Completed"
                />
                <KYC
                  name="Frank Mensah"
                  description="Driver’s License Uploaded"
                  date="12 Sept"
                  status="Completed"
                />
                <KYC
                  name="Frank Mensah"
                  description="Driver’s License Uploaded"
                  date="12 Sept"
                  status="Completed"
                />
                <KYC
                  name="Frank Mensah"
                  description="Driver’s License Uploaded"
                  date="12 Sept"
                  status="Completed"
                />
                <KYC
                  name="Frank Mensah"
                  description="Driver’s License Uploaded"
                  date="12 Sept"
                  status="Completed"
                />
                <KYC
                  name="Frank Mensah"
                  description="Driver’s License Uploaded"
                  date="12 Sept"
                  status="Completed"
                />
                <KYC
                  name="Frank Mensah"
                  description="Driver’s License Uploaded"
                  date="12 Sept"
                  status="Completed"
                />
                <KYC
                  name="Frank Mensah"
                  description="Driver’s License Uploaded"
                  date="12 Sept"
                  status="Completed"
                />
                <KYC
                  name="Frank Mensah"
                  description="Driver’s License Uploaded"
                  date="12 Sept"
                  status="Completed"
                />
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
