/* eslint-disable react/no-unescaped-entities */
/* eslint-disable require-jsdoc */
import React from "react";
import { Formik, Field, Form, ErrorMessage } from "formik";
import * as Yup from "yup";
import Head from "next/head";
import question from "../assets/forgotpassword.png";
import Image from "next/image";
import logo from "../assets/signinlogo.png";
import Link from "next/link";

type SignInProp = {
  email?: string;
  password?: string;
  checked: any;
};

export default function SignIn() {
  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* Code goes into the main tag */}
      <main className=" xg:min-h-screen">
        <section className="flex w-full">
          <div id="signin" className="w-[50%] bg-contain bg-no-repeat h-screen">
            <Image
              className="mt-[64px] max-2xl:mt-[44px] max-2xl:w-44 ml-[41px]"
              src={logo}
              alt="signin logo"
            />

            <p className="text-[48px] mt-[22%] ml-[41px] max-2xl:text-[38px] max-2xl:w-[400px] max-2xl:leading-[48px] leading-[64px] text-white font-bold w-[500px]">
              Drive now with Eganow
            </p>
            <p className="text-white pt-5 w-[510px] max-2xl:text-sm max-2xl:w-[460px] font-normal text-base ml-[41px] leading-[1.4rem]">
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, seddiam
              nonummy nibh euismod tincidunt ut laoreet dolore magnaaliquam erat
              volutpat. veniam. quis nostrud exerci tation
            </p>
          </div>
          <div className="w-[50%] dark:bg-dm-700 h-screen ">
            <Formik<SignInProp>
              initialValues={{
                email: "",
                password: "",
                checked: [],
              }}
              validationSchema={Yup.object({
                email: Yup.string()
                  .email(
                    "Oops! That email address doesn't seem right. Please double-check and try again."
                  )
                  .required("Required"),
                password: Yup.string().required(" Password Required"),
              })}
              onSubmit={(values) => {
                alert(JSON.stringify(values));
              }}
            >
              {({ handleSubmit, values, handleChange, setFieldValue }) => (
                <Form onSubmit={handleSubmit}>
                  <div className="mt-[24%] ml-[20%] ">
                    <p className="text-[#262626] dark:text-white max-2xl:text-[28px] font-medium text-[32px] leading-[40px]">
                      Sign in
                    </p>

                    <div className="mt-6 max-2xl:mt-4 ">
                      <Field
                        type="email"
                        id="email"
                        className="border placeholder-[#BFBFBF] dark:placeholder-dm-300 border-gray-300 dark:border-0 dark:bg-dm-600 text-gray-900 dark:text-white text-sm rounded block w-[75%] max-2xl:p-1.5 p-2.5"
                        placeholder="Mail"
                        value={values.email}
                        onChange={handleChange}
                      />
                      <p className="font-medium text-xs text-[#DC4A41]">
                        <ErrorMessage name="email" />
                      </p>
                    </div>

                    <div className=" mt-6 max-2xl:mt-5">
                      <Field
                        type="password"
                        id="password"
                        className="border placeholder-[#BFBFBF] dark:placeholder-dm-300 border-gray-300 dark:border-0 dark:bg-dm-600 text-gray-900 dark:text-white text-sm rounded block w-[75%] max-2xl:p-1.5 p-2.5"
                        placeholder="Password"
                        value={values.password}
                        onChange={handleChange}
                      />
                      <p className="font-medium text-xs text-[#DC4A41]">
                        <ErrorMessage name="password" />
                      </p>
                    </div>

                    <div className="mt-6 max-2xl:mt-4">
                      <div className="flex items-center mr-auto  h-5">
                        <Field
                          type="checkbox"
                          name="checked"
                          value="remember"
                          className="border-[#007AF5] dark:bg-dm-600 dark:border-dm-500 text-[#007AF5] cursor-pointer max-2xl:w-3 max-2xl:h-3 focus:ring-0 focus:ring-offset-0 focus:outline-none"
                        />

                        <label
                          htmlFor="remember"
                          className="ml-2 text-sm max-2xl:text-xs font-normal text-[#818187] dark:text-dm-300"
                        >
                          Remember me
                        </label>
                      </div>
                    </div>

                    <Link href={"/views/dashboard"}>
                      <button
                        type="button"
                        className="focus:outline-none text-[1.25rem] max-2xl:text-lg text-white bg-[#007AF5] font-medium rounded py-2 max-2xl:py-1 w-[75%] mb-2 max-2xl:mt-4 mt-6 cursor-pointer"
                      >
                        Sign In
                      </button>
                    </Link>

                    <div className="flex max-2xl:mt-4 mt-6">
                      <Image src={question} alt="question mark icon" />
                      <Link
                        href="/views/Homeowner/forgotPassword"
                        className="underline underline-offset-2 ml-2 text-xs text-[#0129F9]"
                      >
                        Forgot Your Password?
                      </Link>
                    </div>
                  </div>
                </Form>
              )}
            </Formik>
          </div>
        </section>
      </main>
    </>
  );
}
