/* eslint-disable require-jsdoc */
/* eslint-disable react/no-unescaped-entities */
import React from "react";
import { useEffect, useState } from "react";
import Modal from "react-modal";
import Head from "next/head";
import Layout from "../../../components/layout";
import ListOfVehiclesTiles from "../../../components/Vehicle/ListOfVehiclesTiles";
import { VehicleTrackerTable } from "../../../components/Vehicle/VehicleTracker/VehicleTrackerTable";
import vehicle from "../../../assets/vehicle.svg";
import repair from "../../../assets/repair.svg";
import payment from "../../../assets/payments.png";
import bell from "../../../assets/bell_icon.png";
import plus from "../../../assets/plus.png";
import VehicleTrackerTiles from "@/components/Vehicle/VehicleTracker/VehicleTrackerTiles";
import Header from "@/components/header";

export default function VehicleTracker() {
  const [modalIsOpen, setModalIsOpen] = useState(false);

  const openModal = () => {
    setModalIsOpen(true);
  };

  const closeModal = () => {
    setModalIsOpen(false);
  };

  const customStyles = {
    content: {
      top: "50%",
      left: "50%",
      right: "auto",
      bottom: "auto",
      marginRight: "-50%",
      transform: "translate(-50%, -50%)",
      padding: "0",
      width: "308px",
      height: "183px",
      borderRadius: "8px 8px 8px 8px",
      backgroundColor: "white",
    },
    overlay: {
      background: "#0000008F",
    },
  };

  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header name="Vehicles Tracker" />
        </div>
      </div>
      <Layout>
        <Head>
          <title>Vehicle Tracker</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full ">
            <div className="flex space-x-4 grow m-5">
              <VehicleTrackerTiles
                icon={vehicle}
                entity1="Total Vehicles"
                entity1value={1250}
                entity1differential={+15.8}
                entity2="Allocated Vehicles"
                entity2value={1180}
                entity3="Unallocated Vehicles"
                entity3value={70}
              />
              <VehicleTrackerTiles
                icon={repair}
                entity1="Completed Issues"
                entity1value={20}
                entity1differential={-5.8}
                entity2="Active Issues"
                entity2value={450}
                entity3="Out of service"
                entity3value={15}
              />
            </div>

            <div className="bg-white rounded-lg mx-5 px-[10px] mb-12 mt-6 ">
              <div className="flex justify-between ">
                <h4 className="text-[#262626] font-medium text-[22px] leading-[30px] pt-4 ">
                  Vehicle Tracker
                </h4>
              </div>
              <VehicleTrackerTable />
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
