/* eslint-disable require-jsdoc */
/* eslint-disable react/no-unescaped-entities */
import React from "react";
import Head from "next/head";
import Header from "../../../components/header";
import Layout from "../../../components/layout";
import { AllDriversTable } from "../../../components/Drivers/AllDriversTable";
import AllDriverTiles, { AllDriverTiles1 } from "@/components/Drivers/DriverTiles";
import driver from "../../../assets/driver.svg";
import vehicle from "../../../assets/vehicle.svg";
import payment from "../../../assets/payment.svg";

export default function AllDrivers() {
  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header name="Drivers" />
        </div>
      </div>
      <Layout>
        <Head>
          <title>All Drivers</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full ">
            <div className="flex space-x-4 grow m-5">
              <AllDriverTiles
                icon={vehicle}
                entity1="Total Vehicles"
                entity1value={1250}
                entity1differential={+15.80}
                entity2="Active Vehicles"
                entity2value={1180}
                entity2differential={+4.90}
                entity3="Damaged"
                entity3value={70}
                entity3differential={-4.90}
              />
              <AllDriverTiles
                icon={driver}
                entity1="Total Drivers"
                entity1value={1250}
                entity1differential={+15.80}
                entity2="Online Drivers"
                entity2value={1180}
                entity3="Offline Drivers"
                entity3value={70}
                entity3differential={-4.90}
                entity2differential={-4.90}
              />
              <AllDriverTiles1
                icon={payment}
                entity1="Total Payments"
                entity1value={450}
                entity2="Completed"
                entity2value={445}
                entity3="Failed"
                entity3value={5}
              />
            </div>

            {/* Table */}
            <div className=" bg-white rounded-lg px-[10px] mx-5 mt-[24px]">
              <h3 className="font-medium pl-2 pt-5 text-[#262626] text-[22px] leading-[30px] ">
                List of Drivers
              </h3>

              <div className="relative overflow-x-auto bg-white mb-[144px] sm:rounded-t-md">
                <AllDriversTable />
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
