/* eslint-disable require-jsdoc */

/* eslint-disable react/no-unescaped-entities */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import Head from "next/head";
import Layout from "../../../components/layout";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import { AllDriversTable } from "../../../components/Drivers/AllDriversTable";
import AllDriverTiles from "@/components/Drivers/DriverTiles";
import Link from "next/link";
import Image from "next/image";
import driver from "../../../assets/driver_icon.png";
import vehicle from "../../../assets/vehicle_icon.png";
import payment from "../../../assets/payments.png";
import { DashboardTiles1 } from "@/components/tiles";
import DashboardTiles from "@/components/tiles";
import AccountMenu from "@/components/headerDropdown";
import { Grid } from "@mui/material";
// import { gridSpacing } from "../components/revenueChart/constant";
import BasicStacking from "@/components/stackedChart";
import Header from "@/components/header";

export default function AllDrivers() {
  return (
    <>
      <Header name="Drivers" />
      <Layout>
        <Head>
          <title>All Drivers</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          {/* Bottom menu */}
          <section className="w-full ">
            <div className="flex space-x-4 grow m-5">
              <AllDriverTiles
                icon={vehicle}
                entity1="Total Vehicles"
                entity1value={1250}
                entity1differential="+15.80%"
                entity2="Active Vehicles"
                entity2value={1180}
                entity2differential="+4.90%"
                entity3="Damaged"
                entity3value={70}
                entity3differential="-4.90%"
              />
              <AllDriverTiles
                icon={driver}
                entity1="Total Drivers"
                entity1value={1250}
                entity1differential="+15.80%"
                entity2="Online Drivers"
                entity2value={1180}
                entity3="Offline Drivers"
                entity3value={70}
                entity3differential="-4.90%"
              />
              <AllDriverTiles
                icon={payment}
                entity1="Total Payments"
                entity1value={450}
                entity2="Completed"
                entity2value={445}
                entity3="Failed"
                entity3value={5}
              />
            </div>

            {/* Table */}
            <div className=" bg-white rounded-lg mx-5 mt-[24px]">
              <h3 className="font-medium pl-2 pt-5 text-[#262626] text-[22px] leading-[30px] ">
                List of Drivers
              </h3>

              <div className="relative overflow-x-auto bg-white sm:rounded-t-md">
                <AllDriversTable />
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
