/* eslint-disable require-jsdoc */
/* eslint-disable react/no-unescaped-entities */
import React from "react";
import { useEffect, useState } from "react";
import KYC from "@/components/driverKYC";
import { Formik, Field, Form, ErrorMessage } from "formik";
import * as Yup from "yup";
import Head from "next/head";
import Layout from "../../../../components/layout";
import blueline from "../../../../assets/blueline.svg";
import greyline from "../../../../assets/greyline.svg";
import StyledDropzone, {
  VehicleImagesDropzone,
  VehicleImagesDropzone1,
} from "../../../../components/dropzone";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import AllDriverTiles from "@/components/Drivers/DriverTiles";
import Link from "next/link";
import Image from "next/image";
import CheckOutlinedIcon from "@mui/icons-material/CheckOutlined";
import greenline from "../../../../assets/greenline.svg";
import info from "../../../../assets/info_icon.png";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import driver from "../../../assets/driver_icon.png";
import plus from "../../../../assets/plus.png";
import vehicle from "../../../assets/vehicle_icon.png";
import payment from "../../../assets/payments.png";
import { DashboardTiles1 } from "@/components/tiles";
import DashboardTiles from "@/components/tiles";
import AccountMenu from "@/components/headerDropdown";
import BasicStacking from "@/components/stackedChart";
import Header from "@/components/header";

type UploadModel = {
  documents?: any;
};

export default function VehicleImages(prop: UploadModel) {
  const phoneRegExp =
    /^((\+[1-9]{1,4}[ -]?)|(\([0-9]{2,3}\)[ -]?)|([0-9]{2,4})[ -]?)*?[0-9]{3,4}[ -]?[0-9]{3,4}$/;

  return (
    <>
      <div className="flex w-full">
        <div className="w-full z-10">
          <Header name="Add Vehicle" />
        </div>
      </div>
      <Layout>
        <Head>
          <title>Add New Driver</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        {/* Code goes into the main tag */}
        <main className="bg-[#F2F2F2] w-full xg:min-h-screen">
          <section className="bg-[#FFFFFF] rounded-lg m-[19px] p-4">
            <div className="pb-4">
              <h3 className="font-medium text-[22px] leading-[30px] text-[#262626]">
                Add Vehicle
              </h3>
              <p className="text-[#737373] font-medium leading-[30px] text-base ">
                Complete this form to add a vehicle.
              </p>
            </div>
            {/* Timeline */}
            <div className="flex py-6 px-[44px] border-y items-center">
              <div className="bg-[#0C9064] flex items-center justify-center  w-8 h-8 text-white rounded-[100%] ">
                <CheckOutlinedIcon fontSize="small" />
              </div>
              <p className="pl-[10px] text-nowrap font-bold text-sm leading-[30px] text-[#0C9064]">
                Vehicle Details
              </p>
              <Image
                src={greenline}
                alt="blue timeline"
                className="w-[23%] grow ml-1"
              />
              <div className="bg-[#007AF5] flex items-center justify-center ml-1 w-8 h-8 text-white rounded-[100%] ">
                2
              </div>
              <p className="pl-[10px] text-nowrap font-bold text-sm leading-[30px] text-[#007AF5]">
                Vehicle Images
              </p>
              <Image
                src={greyline}
                alt="blue timeline"
                className="w-[23%] grow ml-1"
              />
              <div className="bg-[#8C8C8C] flex items-center justify-center ml-1 w-8 h-8 text-white rounded-[100%] ">
                3
              </div>
              <p className="pl-[10px] text-nowrap font-bold text-sm leading-[30px] text-[#8C8C8C]">
                Registration Details
              </p>
            </div>

            <div className="mt-2 mb- border-0">
              <Formik<UploadModel>
                initialValues={{}}
                validationSchema={Yup.object({})}
                onSubmit={async (values) => {
                  alert(JSON.stringify(values, null, 2));
                }}
              >
                {({ handleSubmit, values, handleChange, setFieldValue }) => (
                  <Form onSubmit={handleSubmit} className="bg-white border-0 ">
                    <div className="mt-4">
                      <h5>Vehicle Images</h5>
                      <p className="text-[#737373] text-sm font-medium leading-[30px] pt-1">
                        Upload images of the Vehicle. For sample images,
                        <Link
                          href={""}
                          className="text-[#0076EC] hover:underline "
                        >
                          {" "}
                          learn more
                        </Link>
                        .
                      </p>
                    </div>
                    {/* dropzones */}
                    <div>
                      <div className="flex w-full gap-x-5 justify-between mt-3">
                        <div className="flex flex-col grow  items-center">
                          <VehicleImagesDropzone />
                          <p className="text-[#737373]  font-medium text-xs leading-[30px] pt-2 ">
                            3/4 View
                          </p>
                        </div>
                        <div className="flex flex-col grow  items-center">
                          <VehicleImagesDropzone />
                          <p className="text-[#737373]  font-medium text-xs leading-[30px] pt-2 ">
                            Front View
                          </p>
                        </div>
                        <div className="flex flex-col grow  items-center">
                          <VehicleImagesDropzone />
                          <p className="text-[#737373]  font-medium text-xs leading-[30px] pt-2 ">
                            Right View
                          </p>
                        </div>
                        <div className="flex flex-col grow  items-center">
                          <VehicleImagesDropzone />
                          <p className="text-[#737373]  font-medium text-xs leading-[30px] pt-2 ">
                            Left View
                          </p>
                        </div>
                        <div className="flex flex-col grow  items-center">
                          <VehicleImagesDropzone />
                          <p className="text-[#737373]  font-medium text-xs leading-[30px] pt-2 ">
                            Rear View
                          </p>
                        </div>
                      </div>
                      <div className="flex mt-9 flex-col justify-start items-center">
                        <VehicleImagesDropzone1 />
                        <p className="text-[#737373] font-medium text-xs leading-[30px] pt-2 ">
                          Dashboard View
                        </p>
                      </div>
                    </div>
                    <div className="flex justify-between mt-7">
                      <Link href={"/views/Vehicles/AddVehicle/VehicleDetails"}>
                        <button
                          type="button"
                          className="text-[#FFFFFF] border bg-[#8C8C8C] rounded-[4px] px-4 border-[#DADADA] focus:outline-none text-sm py-1.5 text-center inline-flex justify-center font-normal items-center"
                        >
                          Back
                        </button>
                      </Link>
                      <Link
                        href={"/views/Vehicles/AddVehicle/RegistrationDetails"}
                      >
                        <button
                          type="button"
                          className="text-[#FFFFFF] border bg-[#007AF5] rounded-[4px] px-4 border-[#DADADA] focus:outline-none text-sm py-1.5 text-center inline-flex justify-center font-normal items-center"
                        >
                          Save & Next
                        </button>
                      </Link>
                    </div>
                  </Form>
                )}
              </Formik>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
